version: 2

sources:
  - name: raw
    description: "Raw source data loaded from external systems."
    database: development  # Replace with your actual Snowflake database name
    schema: dbt_sdev  # Replace with your raw schema name

    tables:
      - name: raw_lease_data
        description: "Raw lease data including lease periods, tenants, and monthly rent."
        columns:
          - name: lease_id
            description: "Unique identifier for each lease."
            tests:
              - unique
              - not_null
          - name: property_id
            description: "Foreign key linking to the property."
            tests:
              - not_null
          - name: tenant_id
            description: "Foreign key linking to the tenant."
          - name: lease_start_date
            description: "Start date of the lease."
          - name: lease_end_date
            description: "End date of the lease."
          - name: monthly_rent
            description: "Monthly rent amount for the lease."

      - name: raw_properties_data
        description: "Raw property data including address and unit details."
        columns:
          - name: property_id
            description: "Unique identifier for the property."
            tests:
              - unique
              - not_null
          - name: property_name
            description: "The name of the property."
          - name: address
            description: "The property address."
          - name: num_units
            description: "Total number of units in the property."

      - name: raw_units_data
        description: "Raw unit-level data including monthly rent and size."
        columns:
          - name: unit_id
            description: "Unique identifier for each unit."
            tests:
              - unique
              - not_null
          - name: property_id
            description: "Foreign key linking the unit to its property."
            tests:
              - not_null
          - name: unit_number
            description: "The specific unit number within a property."
          - name: unit_size_sqft
            description: "Size of the unit in square feet."
          - name: monthly_rent
            description: "Monthly rent amount for the unit."

      - name: raw_rental_apps_data
        description: "Raw rental applications data tracking tenant applications per property."
        columns:
          - name: application_id
            description: "Unique identifier for each rental application."
            tests:
              - unique
              - not_null
          - name: tenant_id
            description: "Foreign key linking to the tenant who applied."
            tests:
              - not_null
          - name: property_id
            description: "Foreign key linking to the property."
            tests:
              - not_null
          - name: application_date
            description: "Date when the rental application was submitted."
          - name: status
            description: "Current status of the rental application (e.g., approved, pending, rejected)."

models:
  - name: stg_leases
    description: "Staging model for lease data with cleaned and standardized fields."
    columns:
      - name: lease_id
        description: "Unique identifier for each lease."
        tests:
          - unique
          - not_null
      - name: property_id
        description: "Foreign key linking to the property."
        tests:
          - not_null
      - name: tenant_id
        description: "Foreign key linking to the tenant."
      - name: lease_start_date
        description: "Start date of the lease."
      - name: lease_end_date
        description: "End date of the lease."
      - name: monthly_rent
        description: "Monthly rent amount for the lease."

  - name: stg_units
    description: "Staging model for unit data, standardizing rents and sizes."
    columns:
      - name: unit_id
        description: "Unique identifier for each unit."
        tests:
          - unique
          - not_null
      - name: property_id
        description: "Foreign key linking the unit to its property."
        tests:
          - not_null
      - name: unit_number
        description: "The specific unit number within a property."
      - name: unit_size_sqft
        description: "Size of the unit in square feet."
      - name: monthly_rent
        description: "Monthly rent amount for the unit."

  - name: stg_rental_apps
    description: "Staging model for rental applications with cleaned and formatted statuses."
    columns:
      - name: application_id
        description: "Unique identifier for each rental application."
        tests:
          - unique
          - not_null
      - name: tenant_id
        description: "Foreign key linking to the tenant who applied."
        tests:
          - not_null
      - name: property_id
        description: "Foreign key linking to the property."
        tests:
          - not_null
      - name: application_date
        description: "Date when the rental application was submitted."
      - name: application_status
        description: "Standardized status of the application (approved, rejected, pending)."

  - name: dim_properties
    description: "Dimension model containing property details, rent statistics, and application data."
    columns:
      - name: property_id
        description: "Unique identifier for the property."
        tests:
          - unique
          - not_null
      - name: property_name
        description: "The name of the property."
      - name: address
        description: "The property address."
      - name: num_units
        description: "Total number of units in the property."
      - name: avg_rent
        description: "Average rent for units in the property."
      - name: occupancy_rate
        description: "Percentage of occupied units in the property."
      - name: total_applications
        description: "Total rental applications for the property."
      - name: approved_applications
        description: "Number of approved applications."
      - name: rejected_applications
        description: "Number of rejected applications."
      - name: pending_applications
        description: "Number of applications still pending."
      - name: approval_rate
        description: "Percentage of applications that got approved."

  - name: fct_leases
    description: "Fact table tracking lease details including lease duration and rent."
    columns:
      - name: lease_id
        description: "Unique identifier for each lease."
        tests:
          - unique
          - not_null
      - name: property_id
        description: "Foreign key linking to the property."
        tests:
          - not_null
      - name: tenant_id
        description: "Foreign key linking to the tenant."
      - name: lease_start_date
        description: "Start date of the lease."
      - name: lease_end_date
        description: "End date of the lease."
      - name: monthly_rent
        description: "Monthly rent amount for the lease."
      - name: lease_duration_months
        description: "Total duration of the lease in months."
      - name: lease_status
        description: "Whether the lease is active or expired."
      - name: total_lease_value
        description: "Total value of the lease contract."
